### ISSUE TITLE
the object in the mapping is not an iri

### ISSUE THREAD

**Issue by jimenbian** [ontop/ontop-examples#1]
I have imported the mysql data and owl of aaai-2016-ontopprox successfully. But when I tried to start the reasoner, I found this problem

![Uploading problem.png…]()

. I thought there is something wrong with the file "univ-bench-dl.obda", could you tell me how to fix this bug? 

THANKS. 
Garvin

**Comment by skomlaebri** [comment]
Mapping works until the version of ontop 1.61.1
We changed the syntax of the obda mapping file  from ontop release 1.17
Attached the new mapping file.
[univ-bench-dl.obda.txt](https://github.com/ontop/ontop-examples/files/171790/univ-bench-dl.obda.txt)
